### ISSUE TITLE
Comments tab is broken on the admin

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#312]
Step 1. Leave a comment on a task in the frontend
Step 2. Visit the admin
Step 3. The Data tab works great:

![screen shot 2018-01-23 at 7 37 20 am](https://user-images.githubusercontent.com/26938537/35276140-58fa9af4-0010-11e8-9e92-6e5c8426c027.png)

Step 4. The Comments tab is broken

![screen shot 2018-01-23 at 7 37 24 am](https://user-images.githubusercontent.com/26938537/35276148-6210219a-0010-11e8-8468-a60bd1d720f7.png)

**Comment by deenison** [comment]
This issue was confirmed on `v1.13.5` but it was fixed on `v1.13.6`. Could you confirm please? @upstreamplugin

**Comment by upstreamplugin** [comment]
Still broken. It works for items with no comments, but I do still see the issue on 1.13.6, at least when a comment has already been added

Step 1. Add a comment on the front of the site
Step 2. Go to the admin area and check the "Comment" tab
