### ISSUE TITLE
Project dates missing inside /projects/ popup

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#750]
First you see the dates:

<img width="380" alt="Screen Shot 2019-04-30 at 11 59 12 AM" src="https://user-images.githubusercontent.com/3868028/56975737-6b5ed700-6b3f-11e9-9104-16b4ac3822a3.png">

Now you don't (inside the pop-up)

<img width="629" alt="Screen Shot 2019-04-30 at 12 00 11 PM" src="https://user-images.githubusercontent.com/3868028/56975793-87627880-6b3f-11e9-96af-6bcec2bf3ffb.png">

**Comment by stevejburge** [comment]
Same thing is true with some custom fields. For example a "Tag" custom field has data that shows on the screen.

Click to edit, and the custom field is empty

<img width="660" alt="Screen Shot 2019-05-17 at 8 50 11 AM" src="https://user-images.githubusercontent.com/3868028/57929255-cf440800-7880-11e9-88b5-83a236b1b473.png">

**Comment by stevejburge** [comment]
Reported and confirmed by a customer

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
May I contact with original developer?
I have one question for it.
I have debugged it, so I found problem.

Front-Edit / includes / class-up-frontend-process.php : Line 846
$value = array_key_exists('end',
                $_POST) && ! empty($_POST['end']) ? upstream_date_unixtime(sanitize_text_field($_POST['end'])) : '';
            update_post_meta($projectId, '_upstream_project_end', $value);
It saved with unix time (1559433600)

**Comment by andergmartins** [comment]
Hi @sergeidevstar001, 
Yes, we still have a lot of legacy code on it. All dates are saved as unix time in UpStream. I honestly don't like this approach, but we were not able to refactor that yet.
I can reproduce the bug. I can actually save the start and end dates, but when I open the popup to edit those fields are empty. 
The ajax is returning the correct data, so the error is in the JS code.
I think the problem is data type conflict. The date is Unixtime, a integer, but returned as string. And there is a method getUTCDate which sums the timezone offset to the date, and being an operation between a string and integer the result would be a concatenation, not integer sum. 

Please, could you review this line?

https://github.com/upstreamplugin/UpStream-Frontend-Edit/blob/master/assets/js/project.js#L25

I think if we force datetime to be an integer, the operation will return the correct value.

**Comment by sergeidevstar001** [comment]
Thanks, @andergmartins 
I already have checked it, but it returns invalid date.
![image](https://user-images.githubusercontent.com/39214560/58726009-303c1600-8413-11e9-9bd5-18b1c58ad2a7.png)

**Comment by sergeidevstar001** [comment]
Hi, @andergmartins 
I found problem.
Thanks for your help.
It returned string, so I convert it to int.
var offset = new Date().getTimezoneOffset() * 60;
        // Remove the offset.
        datetime = parseInt(datetime) + parseInt(offset);

**Comment by sergeidevstar001** [comment]
Fixed

**Comment by sergeidevstar001** [comment]
Another issue related with #775 
If #775 is fixed, it will be fine.

**Comment by andergmartins** [comment]
👍 sure thing. Glad to help.

I'm checking the other issues you mention.
Did you commit the change? 

Thanks

**Comment by sergeidevstar001** [comment]
Fixed

**Comment by andergmartins** [comment]
The mentioned fix https://github.com/upstreamplugin/UpStream/issues/750#issuecomment-499519446 was added on this commit: https://github.com/upstreamplugin/UpStream-Frontend-Edit/commit/5ff18aa3590aa46a1b26e943125bca32a5bac275

**Comment by andergmartins** [comment]
It seemed to work on my first review, but after installing again in another site, I can confirm the bug is still there.

**Comment by sergeidevstar001** [comment]
Hi, @andergmartins 
I think it's fixed already by another fixing...
Could you check it again for me?
