### ISSUE TITLE
Activity numbers not accurate in frontend or admin

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#755]
Admin:

<img width="605" alt="Screen Shot 2019-05-01 at 3 43 17 PM" src="https://user-images.githubusercontent.com/3868028/57038457-ec919900-6c27-11e9-9263-f1f54e614ac2.png">

Frontend:

![Screen-Shot-2019-04-25-at-9-16-40-AM](https://user-images.githubusercontent.com/3868028/57038491-08953a80-6c28-11e9-8bc6-587024bd5851.png)

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
I checked it several times on localhost, but I didn't found any problem.
I debugged it, but it works good.
Please check it again for me.

**Comment by andergmartins** [comment]
@sergeidevstar001 I see an issue with the "Assigned to me" (front-end) or "Mine" (back-end).
You can reproduce on the following demo site, project Design A New Website:


http://busy-mongoose.w5.wpsandbox.pro/projects/designing-a-new-website/

```
Login: http://busy-mongoose.w5.wpsandbox.pro/wp-admin/ 
Username: demo 
Password: 8wNT2o5o5HTa
```
### Milestones

Partially good.

#### Front-end
<img width="902" alt="Screen Shot 2019-06-11 at 16 59 20" src="https://user-images.githubusercontent.com/407131/59302478-6f1b6880-8c6a-11e9-80ee-d883ea501fa9.png">

#### Back-end
<img width="741" alt="Screen Shot 2019-06-11 at 17 01 30" src="https://user-images.githubusercontent.com/407131/59302571-9eca7080-8c6a-11e9-98be-352ed56c9719.png">

### Tasks

Broken.

#### Front-end
<img width="1070" alt="Screen Shot 2019-06-11 at 17 07 33" src="https://user-images.githubusercontent.com/407131/59302966-932b7980-8c6b-11e9-8b6f-dd4bdbc08c88.png">

#### Back-end
<img width="862" alt="Screen Shot 2019-06-11 at 17 08 59" src="https://user-images.githubusercontent.com/407131/59303012-acccc100-8c6b-11e9-8eb8-974ba4829ef3.png">

### Bugs

Broken.

#### Front-end
<img width="1029" alt="Screen Shot 2019-06-11 at 17 10 24" src="https://user-images.githubusercontent.com/407131/59303109-e271aa00-8c6b-11e9-824d-dff37d547f4e.png">

#### Back-end
<img width="804" alt="Screen Shot 2019-06-11 at 17 21 37" src="https://user-images.githubusercontent.com/407131/59303837-6d9f6f80-8c6d-11e9-8e86-92c245b1e456.png">

**Comment by sergeidevstar001** [comment]
Problem :
upstream / includes / admin / metaboxes / metabox-functions.php : Line 173, 194
if ( ..... && ((int)$row['assigned_to'] === $user_id) )
@andergmartins , may I remove the code?
I think $user_id is array of all users and $row['assigned_to'] is array of selected users, so it seems wrong.
Will wait for your review.

**Comment by andergmartins** [comment]
@sergeidevstar001 you are right, just make sure the $row['assigned_to'] is an array.

**Comment by sergeidevstar001** [comment]
Thanks, but it can't resolve current problem by change $row['assigned_to'] to array.
Because if logged in with admin, $user_id have one value, it's int value
if logged custom users, $user_id have array value.
You can see   $user_id  = (int)get_current_user_id();  on  upstream / includes / admin / metaboxes / metabox-functions.php : Line 149, but it's get array. It's problem.

**Comment by sergeidevstar001** [comment]
Thanks, but I don't understand.
array === int (is it possible?)

**Comment by andergmartins** [comment]
Sorry, I misread something.

The way the code is, $row['assigned_to'] can be an array, or integer. That is why the current code has a check for array: `(is_array($assignedTo) && in_array($user_id, $assignedTo)` and for int: `((int)$row['assigned_to'] === $user_id)`. 

`$user_id` is an integer. Please, check this line:
https://github.com/upstreamplugin/UpStream/blob/development/includes/admin/metaboxes/metabox-functions.php#L149

**Comment by sergeidevstar001** [comment]
@andergmartins 
I got it, Thanks

**Comment by sergeidevstar001** [comment]
Fixed it.
I changed && to || (And to Or)

**Comment by andergmartins** [comment]
Sorry, not fully fixed yet. The admin looks better, but testing again before releasing I still see issues in the front-end.

<img width="1279" alt="Screen Shot 2019-07-02 at 17 57 00" src="https://user-images.githubusercontent.com/407131/60546089-ffd9e700-9cf2-11e9-956f-f94fdf196270.png">

**Comment by sergeidevstar001** [comment]
Fixed.

**Comment by andergmartins** [comment]
@sergeidevstar001 I still see errors in the Bugs section:

<img width="1049" alt="Screen Shot 2019-07-16 at 11 51 52" src="https://user-images.githubusercontent.com/407131/61305090-97920780-a7c0-11e9-9f65-01c9e0603733.png">

On the screenshot, it should display 1 assigned bug for the current user. And it is now displaying some error messages. Probably not related to your last fix. Maybe just something that wasn't noticed before.
